### ISSUE TITLE
Jetpack Compose

### ISSUE THREAD

**Issue by viktorisacenko** [google/modernstorage#28]
Hey, is there a plan for jetpack compose compatibility?

**Comment by yrezgui** [comment]
Hi @viktorisacenko, ModernStorage doesn't have dependencies on the UI framework, so it's already working with Jetpack Compose! The only possible issue (I didn't verify) is we're relying currently on Kotlin 1.4.32 while Compose has moved to 1.5.x. We'll migrate to it next week.

**Comment by yrezgui** [comment]
Quick update: I can't update ModernStorage to Kotlin 1.5.x at the moment due to a compiler bug with `kotlin.Result` type (See https://github.com/google/modernstorage/pull/24).
I should release the `alpha02` version this week. If you can test it in a Kotlin 1.5 project, it would be great to see if there are any issue.

**Comment by yrezgui** [comment]
Well the core modules have been rewritten and the sample is fully written in Compose, I guess I can close this issue. Feel free to re-open it if something is missing
