### ISSUE TITLE
[Filesystem] Add support for Files.probeContentType

### ISSUE THREAD

**Issue by yrezgui** [google/modernstorage#39]
The method `Files.probeContentType` doesn't seem to work with `ContentPath`. See documentation [here](https://developer.android.com/reference/java/nio/file/Files#probeContentType(java.nio.file.Path))

**Comment by nic0lette** [comment]
Can you add a stack trace or something for how this fails? I added tests (to my WIP branch) for `Files.probeContentType` and it worked without me adding any code, which made me suspicious.

**Comment by nic0lette** [comment]
Ah, I see now. It's impossible to load a custom implementation of `FileTypeDetector` because our detector would be in the app's APK but the system only looks in [the system's classpath](https://cs.android.com/android/platform/superproject/+/master:libcore/ojluni/src/main/java/java/nio/file/Files.java;l=1556-1557) for the service loader data.

If the file extension matches the correct mime type it works. If it doesn't, then this method will either return the wrong values or null, unfortunately.
